import 'video_content.dart';

final List<VideoContent> data = <VideoContent>[

  VideoContent("Secret Location",
      "We are a content studio for emerging platforms.\nSecret Location combines cutting-edge technology with traditional storytelling to create powerful experiences.",
      ["graphics/example_tile/example_layer5.png", "graphics/example_tile/example_layer4.png", "graphics/example_tile/example_layer3.png", "graphics/example_tile/example_layer2.png", "graphics/example_tile/example_layer1.png"],
      60,
      "http://www.sample-videos.com/video/mp4/720/big_buck_bunny_720p_20mb.mp4",
      "graphics/playblue.png"),

  VideoContent("Blaster of the Universe Trailer",
      "Blasters of the Universe is the first of its kind, bringing the bullet hell genre into first person VR. Intense gameplay is heavily reliant on physical movement, requiring the player to duck, dodge, twist, turn, and maneuver their way through tons of enemies and hundreds of bullets.",
      ["graphics/example_tile/example_layer5.png", "graphics/example_tile/example_layer4.png", "graphics/blasters@2x.png", "graphics/blasters@2x.png"],
      60,
      // Example content sourced from https://github.com/SamsungInternet/examples
      'https://github.com/SamsungInternet/examples/blob/master/360-video/paris-by-diego.mp4?raw=true',
      "graphics/playblue.png"),
  VideoContent("Meditation in Nature",
      "Meditate in nature, the most relaxing place to meditate. Peacefully clear your mind for meditation through meditation.",
      ["graphics/example_tile/example_layer5.png", "graphics/example_tile/example_layer4.png", "graphics/meditation@2x.png", "graphics/meditation@2x.png"],
      60,
      "http://www.sample-videos.com/video/mp4/720/big_buck_bunny_720p_20mb.mp4",
      "graphics/playblue.png"),
  VideoContent("Canada",
      "O Canada!\nOur home and native land!\nTrue patriot love in all of us command.\nCar ton bras sait porter l'épée,\nIl sait porter la croix!",
      ["graphics/example_tile/example_layer5.png", "graphics/example_tile/example_layer4.png", "graphics/canada@2x.png", "graphics/canada@2x.png"],
      60,
      "http://www.sample-videos.com/video/mp4/720/big_buck_bunny_720p_20mb.mp4",
      "graphics/playblue.png"),
  VideoContent("Big Buck Bunny",
      "A large and lovable rabbit deals with three tiny bullies, led by a flying squirrel, who are determined to squelch his happiness.",
      ["graphics/example_tile/example_layer5.png", "graphics/example_tile/example_layer4.png", "graphics/panda.png", "graphics/panda.png"],
      60,
      "http://www.sample-videos.com/video/mp4/720/big_buck_bunny_720p_20mb.mp4",
      "graphics/panda.png"),
  VideoContent("Octopus Carpenter: the Movie",
      "To find the octopus carpenter is to discover underwater treasure. The animation has the depth of the ocean itself. The adventure is both fun and fulfilling. And the lessons just keep on swimming.",
      ["graphics/example_tile/example_layer5.png", "graphics/example_tile/example_layer4.png", "graphics/chimera.png", "graphics/chimera.png"],
      60,
      "http://yt-dash-mse-test.commondatastorage.googleapis.com/media/motion-20120802-87.mp4",
      "graphics/playblue.png"),
];
